stack:
    -   - EE_1
EE_1:
    type: Interaction
    base_link: base_link
    distal_link: TCP_gripper_A
    stiffness:
        - 1000.0
        - 1000.0
        - 1000.0
        - 200.0
        - 200.0
        - 200.0
    damping:
        - 0.7
        - 0.7
        - 0.7
        - 0.7
        - 0.7
        - 0.7
